services:  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      sdi_apps:
        ipv4_address: 172.24.0.22

volumes:
  portainer_data:

networks:
  sdi_apps:
    external: true